version: '3.4'

services:
  
  sql.data:
    ports:
      - "5432:5432"
      
  ozontest:
    environment:
      - ConnectionString=Server=sql.data;Database=ozon;User Id=postgres;Password=postgres;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44336
    ports:
      - "52373:80"
      - "44336:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro